import React, { createContext, useState, useContext, ReactNode } from 'react';

// Get the version from the environment (injected by Vite)
const appVersion = process.env.APP_VERSION || '2.7.8';

type Language = 'en' | 'si';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    "appTitle": "MindSight",
    "appSubtitle": `RV TRAINING PROTOCOL v${appVersion}`,
    "rankPromoted": "Rank Promoted",
    "calibrationComplete": "Calibration Complete",
    "continue": "Continue",
    "dojoLockedMsg": "LOCKED",
    "dojoUnlockedMsg": "CALIBRATION COMPLETE",
    "calibrationTask": "INTUITION CALIBRATION",
    "calibrationTaskDesc": "Your overall signal strength is low (< 50%). You must re-calibrate your baseline intuition by correctly predicting 3 Zener cards in a row.",
    "drawingCalibrationTask": "VISUAL MOTOR CALIBRATION",
    "drawingCalibrationDesc": "Your sketch accuracy was low (< 45%), even though your text data was good. You must re-align your hand-eye coordination by replicating 3 visual forms.",
    "completeCalibration": "You must complete the calibration task before exiting.",
    "lowScoreRedirect": "Accuracy below 50%. You must complete the Intuition Calibration task.",
    "lowDrawingRedirect": "Sketch accuracy below 45%. You must complete the Visual Motor Calibration task.",
    "login": "Login",
    "logout": "Sign Out",
    "operator": "Operator",
    "viewer": "Viewer",
    "session": "Session",
    "welcomeBack": "Welcome back",
    "readyToTrain": "Ready to Train?",
    "introAuth": "Initialize a blind session. Follow the 4-step protocol to record your data before feedback.",
    "introGuest": "Sign in to track your progress across devices and analyze your Remote Viewing sessions with AI.",
    "startSession": "START NEW SESSION",
    "startSessionLoading": "FETCHING ONLINE TARGET...",
    "initializing": "INITIALIZING...",
    "signInRegister": "SIGN IN / REGISTER",
    "historyTitle": "Performance History",
    "aiCoachBtn": "Generate AI Coach Report",
    "aiCoachReady": "AI Analysis Ready",
    "aiCoachUnlock": "Complete 3 sessions to unlock personalized training insights.",
    "analyzing": "Analyzing...",
    "generateReport": "Generate Report",
    "regenerateReport": "Refresh Analysis",
    "regenerateAnalysis": "Regenerate Analysis",
    "noHistory": "No history yet.",
    "totalTime": "Total Training Time",
    "viewAnalytics": "View Full Analytics",
    "intuitionDojo": "Intuition Dojo",
    "drawingDojo": "Visual Motor Dojo",
    "sessionLog": "Session Log",
    "logTitle": "Session Log",
    "deleteSession": "Delete Session",
    "confirmDelete": "Are you sure you want to delete this session?",
    "selectMode": "Select Session Mode",
    "modeTraining": "Standard Training",
    "modeTrainingDesc": "AI generates a blind photo target and scores your accuracy immediately.",
    "modeOpen": "Open Exploration",
    "modeOpenDesc": "View a real-world or personal target (e.g., Lost Object, Future Event). No AI scoring.",
    "enterIntent": "Enter Target Intent",
    "intentPlaceholder": "e.g., Location of missing keys, Tomorrow's Headlines...",
    "intentDesc": "Describe what you are looking for. This helps you verify your data later.",
    "startOpenSession": "Start Open Session",
    "level": "Level",
    "division": "Division",
    "currentRank": "Current Rank",
    "nextRank": "Next Rank",
    "rankLocked": "Rank Calibration",
    "rankLockedDesc": "Complete 3 training sessions to establish your baseline accuracy and earn your first rank.",
    "calibrating": "Calibrating",
    "lvl1": "Novice",
    "lvl2": "Apprentice",
    "lvl3": "Initiate",
    "lvl4": "Viewer",
    "lvl5": "Monitor",
    "lvl6": "Operator",
    "lvl7": "Specialist",
    "lvl8": "Expert",
    "lvl9": "Oracle",
    "cap_lvl1": "Establishing the Signal Line. You are learning to distinguish between imagination (AOL) and true sensory signal. Capable of detecting major energetic shifts.",
    "cap_lvl2": "Basic Contrast Detection. You can perceive fundamental dichotomies: Land vs Water, Man-made vs Natural, Dark vs Light.",
    "cap_lvl3": "Sensory Data Acquisition. You can consistently record core sensory gestalts: Colors, Temperatures, Smells, and Textures.",
    "cap_lvl4": "Dimensional Perception. You are beginning to perceive shapes and forms. Capable of sketching basic outlines and spatial relationships.",
    "cap_lvl5": "Reliable Contact. You can reliably describe the main subject of a target. Suitable for basic practice groups and double-blind trials.",
    "cap_lvl6": "Operational Competence. You can identify specific objects and their functions. Capable of describing complex scenes with moderate accuracy.",
    "cap_lvl7": "High-Fidelity Data. You can distinguish between similar objects and describe detailed architectural or mechanical features.",
    "cap_lvl8": "Predictive Viewing. You can perceive events across time. Capable of describing future outcomes with significant statistical deviation.",
    "cap_lvl9": "Omniscient Access. You demonstrate consistently high accuracy across all target types regardless of complexity or shielding.",
    "shrinkCanvas": "Shrink Canvas",
    "expandCanvas": "Expand Canvas",
    "clearCanvas": "Clear Canvas",
    "sketchInstruction": "Use your finger or mouse to draw your visual impressions.",
    "accuracyTrend": "Accuracy Trend",
    "exitSession": "Exit Session",
    "confirmExit": "Are you sure you want to exit? Your current session data will be lost.",
    "stepFocus": "Focus",
    "stepImpressions": "Impressions",
    "stepSketch": "Sketch",
    "stepReview": "Review",
    "trn": "TRN",
    "stage2Title": "Stage 2: Visuals",
    "stage2Desc": "Sketch the primary shapes and forms. Do not label objects yet.",
    "btnBack": "Back",
    "sketchReviewBtn": "Review Data",
    "analyzingDesc": "The AI Monitor is comparing your data against the target...",
    "savingDesc": "Saving session to your secure log...",
    "analysisErrorDesc": "Analysis failed. Please try again.",
    "analyzingTitle": "Analyzing Session...",
    "analyzingOpen": "Analyzing...",
    "btnAnalyzeOpen": "Ask AI Analyst",
    "btnAnalyzeOpenDesc": "Get an interpretation of your sketch/notes without a ground truth.",
    "startFocusSeq": "Start Focus Sequence",
    "btnFocused": "I am Focused",
    "focusDesc": "Clear your mind. Focus on the Target Reference Number (TRN).",
    "focusTip": "Breathe deeply. Visualize the TRN glowing in your mind's eye.",
    "audioMute": "Mute Audio",
    "audioFocus": "Focus Audio",
    "stopFocusSeq": "Stop Focus",
    "breatheIn": "Breathe In",
    "breatheHold": "Hold",
    "breatheOut": "Exhale",
    "stage1Title": "Stage 1: Impressions",
    "stage1Desc": "Record your immediate sensory perceptions. Focus on low-level data.",
    "placeholderNotes": "Colors, textures, smells, temperatures...",
    "btnNextVisuals": "Next: Visuals",
    "helperBtn": "Sensory Helper",
    "helperTip": "Tap words to add them to your notes.",
    "reviewTitle": "Review Data",
    "reviewDesc": "Confirm your session data before submission.",
    "sensoryNotes": "Sensory Notes",
    "noNotes": "No notes provided.",
    "sketchPreview": "Sketch Preview",
    "noSketch": "No sketch provided.",
    "editData": "Edit Data",
    "submitAnalysis": "Submit for Analysis",
    "saveLog": "Save to Log",
    "min": "m",
    "sec": "s",
    "openChat": "Coach Chat",
    "coachReport": "Coach Report",
    "strengths": "Strengths",
    "weaknesses": "Weaknesses",
    "tip": "Tip",
    "feedbackPhase": "Feedback Phase",
    "accuracyScore": "Score",
    "calibrationRequired": "Calibration Required",
    "nextSession": "Next Session",
    "lowScoreWarning": "Low Signal Strength",
    "calibrationDesc": "Your accuracy has dropped below the operational threshold. Please recalibrate.",
    "visualTools": "Visual Tools",
    "modeSplit": "Split",
    "modeOverlay": "Overlay",
    "opacity": "Opacity",
    "invertSketch": "Invert Sketch",
    "visualRecon": "Visual Reconstruction",
    "targetInaccessible": "Target Inaccessible",
    "actualTarget": "Actual Target",
    "aiVisualDesc": "AI Generated Reconstruction based on your data",
    "targetInaccessibleDesc": "This is an OPEN session. The target is unknown or in the future.",
    "targetIntent": "Target Intent",
    "aiPrediction": "AI Prediction",
    "analystReport": "Analyst Report",
    "generatingImage": "Generating...",
    "generateImage": "Generate Visual",
    "yourSketch": "Your Sketch",
    "addRemarks": "Add Remarks",
    "addRemarksDesc": "Add any post-session thoughts or verify if the AI missed a correct detail.",
    "savingReview": "Saving...",
    "remarksSaved": "Saved",
    "saveRemarks": "Save Remarks",
    "aiAnalysis": "AI Analysis",
    "noAnalysis": "No analysis available.",
    "trendTitle": "Performance Trend",
    "backToList": "Back to List",
    "reconstructionDetails": "Visual Details for AI",
    "chatWelcome": "Hello! I am your Remote Viewing instructor. How can I help you improve your practice today?",
    "chatTitle": "Coach Chat",
    "chatPlaceholder": "Ask about CRV protocols or your history...",
    "analyticsTitle": "Analytics",
    "totalSessions": "Total Sessions",
    "avgScore": "Avg Score",
    "bestScore": "Best Score",
    "currentCapabilities": "Current Capabilities",
    "currentCapabilitiesDesc": "Based on your verified training history.",
    "rankRoadmap": "Rank Roadmap",
    "dojoTitle": "Intuition Dojo",
    "dojoDesc": "Train your pure psychic signal recognition.",
    "streak": "Streak",
    "bestStreak": "Best Streak",
    "accuracy": "Accuracy",
    "chance": "Chance",
    "exitDojo": "Exit Dojo",
    "cardCircle": "Circle",
    "cardCross": "Cross",
    "cardWaves": "Waves",
    "cardSquare": "Square",
    "cardStar": "Star",
    "drawingDojoTitle": "Visual Motor Dojo",
    "drawingDojoDesc": "Align your hand with your mind's eye.",
    "drawingDojoInstruct": "Memorize the Shape",
    "drawingDojoDraw": "Replicate the Shape",
    "drawingDojoCheck": "Check Alignment",
    "btnMiss": "Miss",
    "btnMatch": "Match",
    "authFailed": "Authentication Failed",
    "welcomeBackAuth": "Welcome Back",
    "createAccount": "Create Account",
    "displayName": "Display Name",
    "yourName": "Your Name",
    "emailAddress": "Email Address",
    "password": "Password",
    "btnSignIn": "Sign In",
    "btnSignUp": "Sign Up",
    "noAccount": "Don't have an account?",
    "haveAccount": "Already have an account?"
  },
  si: {
    // Basic fallback for Sinhala if needed (minimal)
    "appTitle": "MindSight",
    "appSubtitle": `RV පුහුණු ප්‍රොටෝකෝලය v${appVersion}`,
    "rankPromoted": "නිලය උසස් කරන ලදි",
    "continue": "ඉදිරියට යන්න"
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    // @ts-ignore
    return translations[language][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};